name: portfolio
description: Portfolio Davide Bolzoni
version: 1.0.3+4

dependencies:
  flutter_web: any
  http: ^0.12.0+2
  provider: 
    path: ./pubs/provider/packages/provider
  mobx: 
    path: ./pubs/mobx.dart/mobx
  flutter_mobx: 
    path: ./pubs/mobx.dart/flutter_mobx

dev_dependencies:
  flutter_web_test: any
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

  test: ^1.3.4

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
