name: portfolio_flutter
description: Flutter Base App

version: 3.0.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  cached_network_image: ^3.1.0+1
  cupertino_icons: ^1.0.4
  dio: ^4.0.3
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  injectable: ^1.5.0
  layout: ^0.6.2
  package_info_plus: ^1.3.0
  provider: ^5.0.0
  routemaster: ^0.9.5
  shared_preferences: ^2.0.9
  statsfl: ^2.0.1+1
  uni_links: ^0.5.1
  url_launcher: ^6.0.15

dev_dependencies:
  build_runner: ^2.1.5
  dante: ^0.0.4
  dart_code_metrics: ^4.4.0
  ficcanaso: ^3.0.8
  flutter_native_splash: ^1.3.1
  freezed: ^0.14.5
  import_sorter: ^4.6.0
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/en.json
    - assets/translations/it.json

    - assets/images/profile.png
    - assets/icon.png
    - assets/images/dbbd59.png
    - assets/images/breaking-news.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

import_sorter:
  emojis: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/dbbd59.png
  android: true
  ios: true
  web: true
  android12: true
