name: portfolio_flutter
description: Flutter Base App

version: 2.1.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  bloc: ^7.0.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  freezed_annotation: ^0.14.0
  get_it: ^6.1.1
  google_fonts: ^2.0.0
  injectable: ^1.1.0
  package_info_plus: ^1.0.1
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  statsfl: ^2.0.1-nullsafety
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^1.11.5
  ficcanaso: ^2.0.3
  flutter_launcher_icons: ^0.9.0
  freezed: ^0.14.0+1
  injectable_generator: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - lang/en.json
    - lang/it.json

    - assets/images/profile.png
    - assets/icon.png
    - assets/images/dbbd59.png
    - assets/images/breaking-news.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

import_sorter:
  emojis: true
