name: portfolio
description: Portfolio Davide Bolzoni
version: 1.0.3+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.2
  url_launcher: ^5.4.1
  flutter_launcher_icons: ^0.7.4
  equatable: ^1.0.2  
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  dio: ^3.0.8

dev_dependencies:
flutter: 
  uses-material-design: true
  assets:
    - assets/profilepic.jpg
    - assets/chuck-norris.png
    - assets/chuck-norris-face.png
    
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/Product-Sans-Regular.ttf
        - asset: assets/Product-Sans-Bold.ttf
          weight: 700
        - asset: assets/Product-Sans-Italic.ttf
          style: italic

flutter_icons:
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"
  android: true 
  ios: true 
  adaptive_icon_background: "assets/icon.png" 
  adaptive_icon_foreground: "assets/icon.png"
