name: portfolio_flutter
description: Flutter Base App

version: 2.0.9+4

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  bloc: ^6.1.1
  cached_network_image: ^2.5.0
  connectivity: ^2.0.2
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  flutter_svg: ^0.19.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  google_fonts: ^1.1.1
  injectable: ^1.0.7
  package_info_plus: ^0.6.3
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4
  statsfl: ^1.1.0+3
  url_launcher: ^5.7.10

dev_dependencies:
  bloc_test: ^7.1.0
  build_runner: ^1.10.3
  ficcanaso: ^1.0.1
  flutter_launcher_icons: ^0.8.1
  freezed: ^0.12.6
  import_sorter: ^4.4.1
  injectable_generator: ^1.0.7

flutter:
  uses-material-design: true
  assets:
    - lang/en.json
    - lang/it.json

    - assets/images/profile.png
    - assets/icon.png
    - assets/images/dbbd59.svg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

import_sorter:
  emojis: true
