name: baseapp
description: Flutter Base App

version: 1.3.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

  ######################Dependency Injection######################  
  #https://pub.dev/packages/get_it
  get_it: ^3.1.0

  ######################State Managment######################
  #https://pub.dev/packages/bloc
  bloc: ^3.0.0
  #https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^3.2.0
  
  ######################Library######################
  #https://pub.dev/packages/cached_network_image
  cached_network_image: ^2.0.0
  #https://pub.dev/packages/url_launcher
  url_launcher: ^5.4.1
  #https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.6+1
  #https://pub.dev/packages/dio
  dio: ^3.0.8
  #https://pub.dev/packages/google_fonts
  google_fonts: ^0.3.9
  #https://pub.dev/packages/connectivity
  connectivity: ^0.4.6+2
  #https://pub.dev/packages/provider
  provider: ^4.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    ###Lang###
    - lang/en.json
    - lang/it.json 
    ###Images###
    - assets/images/profile.png
    - assets/images/chuck-norris-face.png
    - assets/images/chuck-norris.png
    ###Configs###
    - config/prod.json
    - config/dev.json
