name: portfolio
description: Portfolio Davide Bolzoni
version: 1.0.3+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.4
  provider: ^3.1.0+1
  url_launcher: ^5.2.5
  flutter_launcher_icons: ^0.7.4
  equatable: ^0.6.1  
  bloc: ^1.0.0
  flutter_bloc: ^1.0.0
  
flutter: 
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/Product Sans Regular.ttf
        - asset: fonts/Product Sans Bold.ttf
          weight: 700
        - asset: fonts/Product Sans Italic.ttf
          style: italic

flutter_icons:
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"
  android: true 
  ios: true 
  adaptive_icon_background: "assets/icon.png" 
  adaptive_icon_foreground: "assets/icon.png"
