name: portfolio_flutter
description: Flutter Base App

version: 1.9.1+6

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  get_it: ^4.0.1
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  cached_network_image: ^2.1.0+1
  url_launcher: ^5.4.5
  shared_preferences: ^0.5.7
  dio: ^3.0.9
  google_fonts: ^1.0.0
  connectivity: ^0.4.8+2
  provider: ^4.0.5
  statsfl: ^0.1.0
  injectable: ^0.4.0
  freezed_annotation: ^0.7.1
  equatable: ^1.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  injectable_generator: ^0.4.0
  build_runner: ^1.10.0
  import_sorter: ^3.0.6
  freezed: ^0.10.9
  mockito: ^4.1.1
  bloc_test: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - lang/en.json
    - lang/it.json 

    - assets/images/profile.png

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icon.png"
  
import_sorter:
  emojis: true
