name: portfolio_flutter
description: Flutter Base App

version: 3.0.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  bloc: ^7.0.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  freezed_annotation: ^0.14.2
  get_it: ^7.1.4
  google_fonts: ^2.1.0
  injectable: ^1.4.1
  layout: ^0.6.2
  package_info_plus: ^1.0.3
  provider: ^5.0.0
  routemaster: ^0.9.4
  shared_preferences: ^2.0.6
  statsfl: ^2.0.1+1
  uni_links: ^0.5.1
  url_launcher: ^6.0.6

dev_dependencies:
  build_runner: ^2.0.4
  dante: ^0.0.1
  ficcanaso: ^2.0.7
  flutter_native_splash: ^1.2.0
  freezed: ^0.14.2
  import_sorter: ^4.6.0
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/en.json
    - assets/translations/it.json

    - assets/images/profile.png
    - assets/icon.png
    - assets/images/dbbd59.png
    - assets/images/breaking-news.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

import_sorter:
  emojis: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/dbbd59.png
  android: true
  ios: true
  web: true
  android12: true
