name: mobx
version: 0.2.1+1
description: "MobX is a library for reactively managing the state of your applications. Use the power of observables, actions, and reactions
to supercharge your Dart and Flutter apps."
authors:
  - Pavan Podila <pavan@pixelingene.com>
  - Joni Katajamäki <joni.katajamaki@gmail.com>
  - Remi Rousselet <darky12s@gmail.com>

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter_web: any

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui