name: -WEB- Build and Release
on:
    push:
      branches:
      - main
      tags:
      - '*'
    workflow_dispatch:
      tags:
      - '*'
    schedule:
      - cron: "0 0 * * *"
jobs:
  build:
    name: Build Web and Deploy
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter channel master
      - run: flutter upgrade
      - run: flutter config --enable-web
      - run: dart lib/get_flutter_info.dart > lib/flutter_info.dart
      - run: flutter build web --release --web-renderer auto
      - run: |
          cd build/web
          git init
          git config --global user.email davide.bolzoni59@gmail.com
          git config --global user.name dbbd59
          git status
          git remote add origin https://${{secrets.TOKEN}}@github.com/dbbd59/portfolio_flutter.git
          git checkout -b gh-pages
          echo "davidebolzoni.com" >> CNAME
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
